version: '3'
services:
  server:
    build: ./server
    container_name: node-api
    ports:
      - "3001:3001"
    networks:
      - chat-network


  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge